# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: protocolist-rbcn_development
  pool: 5
  username: postgres
  password: 123123

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: protocolist-rbcn_test
  pool: 5
  username: postgres
  password: 123123
